import sys
import subprocess
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5.QtCore import QTimer
from PyQt5.QtGui import QImage, QPixmap
import cv2
from pose_ui import Ui_Form  # Importing UI files generated by Qt Designer

from PyQt5 import QtWidgets
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtCore import QThread, pyqtSignal

from body3d_img2pose_demo_gui import pose_estimation_inference

from mmpose.apis import inference_topdown, init_model

import torch

class PoseEstimationThread(QThread):
    original_frame_signal = pyqtSignal(QImage)
    pose_frame_signal = pyqtSignal(QImage)

    def __init__(self, detector, pose_estimator, parent=None):
        super().__init__(parent)

        self.detector = detector
        self.pose_estimator = pose_estimator

        self.running = False

    def run(self):
        self.running = True
        cap = cv2.VideoCapture(0)
        while self.running and cap.isOpened():
            ret, frame = cap.read()
            if not ret:
                break

            # Sending raw frame signal
            rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            h, w, ch = rgb_frame.shape
            q_image_original = QImage(rgb_frame.data, w, h, ch * w, QImage.Format_RGB888)
            self.original_frame_signal.emit(q_image_original)

            # Call pose_estimation_inference to process the frame
            pose_frame = pose_estimation_inference(
                frame,
                self.detector,
                self.pose_estimator
            )

            # Convert to QImage
            pose_rgb_frame = cv2.cvtColor(pose_frame, cv2.COLOR_BGR2RGB)
            h, w, ch = pose_rgb_frame.shape
            q_image_pose = QImage(pose_rgb_frame.data, w, h, ch * w, QImage.Format_RGB888)

            # Sending Pose Estimation Frame Signals
            self.pose_frame_signal.emit(q_image_pose)

        cap.release()

    def stop(self):
        self.running = False
        self.wait()


class MainApp(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.init_ui()
        self.show()

    def init_ui(self):
        self.setWindowTitle("Realtime Pose Estimation")
        self.setFixedSize(1300, 640)

        # Main Window Layout
        widget = QtWidgets.QWidget()
        layout = QtWidgets.QHBoxLayout()
        widget.setLayout(layout)
        self.setCentralWidget(widget)

        # Original camera image
        self.original_label = QtWidgets.QLabel("Camera Feed")
        self.original_label.setFixedSize(640, 480)
        layout.addWidget(self.original_label)

        # Pose Estimation result
        self.pose_label = QtWidgets.QLabel("Pose Estimation Output")
        self.pose_label.setFixedSize(640, 480)
        layout.addWidget(self.pose_label)

        # Initialize the detector and pose estimator
        device = 'cuda:0' if torch.cuda.is_available() else 'cpu'

        det_config='../configs/rtmdet_m_640-8xb32_coco-person.py'
        det_checkpoint='https://download.openmmlab.com/mmpose/v1/projects/rtmpose/rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth'
        pose_config='../configs/rtmw3d-l_8xb64_cocktail14-384x288.py'
        pose_checkpoint='../configs/rtmw3d-l_8xb64_cocktail14-384x288-794dbc78_20240626.pth'

        detector = init_model(det_config, det_checkpoint, device=device)
        pose_estimator = init_model(pose_config, pose_checkpoint, device=device)

        # Initialize Thread
        self.pose_thread = PoseEstimationThread(detector, pose_estimator)
        self.pose_thread.original_frame_signal.connect(self.update_original_image)
        self.pose_thread.pose_frame_signal.connect(self.update_pose_image)

        # Starting a Thread
        self.pose_thread.start()

    def update_original_image(self, q_image):
        self.original_label.setPixmap(QPixmap.fromImage(q_image))

    def update_pose_image(self, q_image):
        self.pose_label.setPixmap(QPixmap.fromImage(q_image))

    def closeEvent(self, event):
        # Stopping a Thread
        self.pose_thread.stop()
        event.accept()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = MainApp()
    sys.exit(app.exec())